- name: install python-pycurl
  apt: pkg=python-pycurl state=present
- name: add repository for openerp
  apt_repository: repo='deb http://nightly.openerp.com/7.0/nightly/deb/ ./' state=present
- name: aptitude update
  apt: update_cache=yes
- name: install openerp
  apt: pkg=openerp state=present force=true
  notify: restart openerp
- include: db.yml
- include: options.yml