- name: disable default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
- name: create nginx site for openerp
  template: src=openerp_site.j2 dest=/etc/nginx/sites-available/openerp_site owner=root group=root mode=0644
  notify: restart nginx
- name: enable nginx site for openerp
  file: src=/etc/nginx/sites-available/openerp_site dest=/etc/nginx/sites-enabled/openerp_site owner=root group=root state=link
  notify: restart nginx