- name: aptitude update
  apt: update_cache=yes
- name: aptitude upgrade
  apt: upgrade=yes

- name: create postgresql user
  postgresql_user: name=openerp password=openerp role_attr_flags=CREATEDB,NOCREATEROLE,NOSUPERUSER
  sudo_user: postgres
  #when: not openerp.db_host
  notify: restart openerp

# - name: stop postgresql server
#   service: name=postgresql state=stopped
#   when: openerp.db_host
#   notify: restart openerp

- name: install python-pycurl
  apt: pkg=python-pycurl state=present

- name: add repository for openerp
  apt_repository: repo='deb http://nightly.openerp.com/7.0/nightly/deb/ ./' state=present
- name: aptitude update
  apt: update_cache=yes
- name: install openerp
  apt: pkg=openerp state=present force=true
  notify: restart openerp

- name: Configure openerp-server.conf
  template: src=../templates/openerp-server.conf.j2 dest=/etc/openerp-server.conf

- name: install nginx
  apt: pkg=nginx state=present
  notify: restart nginx

- name: disable default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
- name: create nginx site for openerp
  template: src=../templates/openerp_site.j2 dest=/etc/nginx/sites-available/openerp_site owner=root group=root mode=0644
  notify: restart nginx
- name: enable nginx site for openerp
  file: src=/etc/nginx/sites-available/openerp_site dest=/etc/nginx/sites-enabled/openerp_site owner=root group=root state=link
  notify: restart nginx

# - name: restart openerp #HANDLER
#   service: name=openerp state=restarted

# - name: restart nginx #HANDLER
#   service: name=nginx state=restarted 
